version: '3.8'

services:
  pgshardA:
    image: pgshard:latest
    container_name: pgshardA
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "5001:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

  pgshardB:
    image: pgshard:latest
    container_name: pgshardB
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "5002:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

  pgshardC:
    image: pgshard:latest
    container_name: pgshardC
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "5003:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres